### ISSUE TITLE
Specify docker registry

### ISSUE THREAD

**Issue by cr4ftx** [FaustXVI/junit5-docker#110]
Hi there,

I wonder if it is possible to use a private registry hosted on a nexus 3 repository.

I see that there is a default docker client but can i use my own client for my need ?

Thanks a lot.

**Comment by FaustXVI** [comment]
Hi, sorry for the delay. So far, we do not support private registry directly, but if your docker daemon is configured to use a private registry, it should work.
We won't add the support, because we stopped the development of this library. Indeed, the (testcontainers project is adding support to JUnit 5)[https://github.com/testcontainers/testcontainers-java/issues/87#issuecomment-272088989] and we want to avoid unnecessary standards.
This library is a small workaround while waiting for testcontainers to fully support JUnit5 but won't evolve.
Thank you for your comprehension.
